import React, { useEffect, useMemo, useRef, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { marked } from 'marked';
import './styles.css';

type Annotation = { id: string; type: 'highlight' | 'freehand' | 'line'; start?: number; end?: number; text?: string; points?: [number, number][]; color?: string };
type Item = { id: string; name: string; valid: boolean; files: Record<string, boolean> };
type Exam = { id: string; name: string; items: Item[] };
type Question = { id?: string; question: string; options: { key: string; text: string }[]; answer: string; explanation?: string };

const uid = () => crypto.randomUUID();
const api = (url: string, init?: RequestInit) => fetch(url, init).then(async r => { if (!r.ok) throw new Error((await r.json()).error || '请求失败'); return r.json(); });

function App() {
  const [exams, setExams] = useState<Exam[]>([]), [selected, setSelected] = useState<{ exam: string; item: string }>(), [data, setData] = useState<any>(), [tool, setTool] = useState<'select'|'highlight'|'freehand'|'line'|'eraser'>('select'), [sidebarOpen, setSidebarOpen] = useState(true);
  const [annotations, setAnnotations] = useState<Annotation[]>([]), [history, setHistory] = useState<Annotation[][]>([]), [future, setFuture] = useState<Annotation[][]>([]), [showAnswers, setShowAnswers] = useState<Record<string, boolean>>({}), [changed, setChanged] = useState(false);
  const materialRef = useRef<HTMLDivElement>(null), canvasRef = useRef<HTMLCanvasElement>(null), drawing = useRef<[number, number][]>([]), start = useRef<[number, number] | null>(null);

  const loadExams = () => api('/api/examinations').then(setExams).catch(() => setExams([]));
  useEffect(() => { loadExams(); const es = new EventSource('/api/events'); es.onmessage = () => setChanged(true); return () => es.close(); }, []);
  useEffect(() => { if (!selected) return; api(`/api/items/${encodeURIComponent(selected.exam)}/${encodeURIComponent(selected.item)}`).then(d => { setData(d); setAnnotations(d.annotations?.annotations || []); setHistory([]); setFuture([]); setShowAnswers({}); }); }, [selected]);
  useEffect(() => { const canvas = canvasRef.current, host = materialRef.current; if (!canvas || !host) return; const resize = () => { canvas.width = host.clientWidth; canvas.height = host.scrollHeight; draw(); }; resize(); const observer = new ResizeObserver(resize); observer.observe(host); return () => observer.disconnect(); }, [data]);
  useEffect(() => { draw(); }, [annotations]);
  const save = (next: Annotation[]) => { setAnnotations(next); if (selected) api(`/api/items/${selected.exam}/${selected.item}/annotations`, { method: 'PUT', headers: {'Content-Type':'application/json'}, body: JSON.stringify({ annotations: next }) }).catch(() => alert('批注保存失败')); };
  const commit = (next: Annotation[]) => { setHistory(h => [...h, annotations]); setFuture([]); save(next); };
  const draw = () => { const c = canvasRef.current, host = materialRef.current; if (!c || !host) return; const ctx = c.getContext('2d')!; ctx.clearRect(0,0,c.width,c.height); ctx.lineWidth = 3; ctx.lineCap='round'; for (const a of annotations) { if (a.type === 'highlight') continue; if (!a.points?.length) continue; ctx.strokeStyle = a.type === 'line' ? '#ef6c47' : '#2e6fdf'; ctx.beginPath(); ctx.moveTo(...a.points[0]); a.points.slice(1).forEach(p => ctx.lineTo(...p)); ctx.stroke(); } };
  const point = (e: React.PointerEvent) => { const r = canvasRef.current!.getBoundingClientRect(); return [e.clientX-r.left, e.clientY-r.top] as [number,number]; };
  const onDown = (e: React.PointerEvent) => { if (tool === 'select' || tool === 'highlight') return; (e.currentTarget as HTMLElement).setPointerCapture(e.pointerId); const p = point(e); start.current=p; drawing.current=[p]; };
  const onMove = (e: React.PointerEvent) => { if (!drawing.current.length) return; const p=point(e); if(tool==='freehand') drawing.current.push(p); drawPreview(); };
  const onUp = () => { if (!drawing.current.length || !start.current) return; const points = tool === 'line' ? [start.current, drawing.current[drawing.current.length-1]] : drawing.current; commit([...annotations, { id: uid(), type: tool as 'freehand'|'line', points }]); drawing.current=[]; start.current=null; };
  const drawPreview = () => { draw(); const c=canvasRef.current, pts=drawing.current; if(!c || !pts.length) return; const ctx=c.getContext('2d')!; ctx.strokeStyle=tool==='line'?'#ef6c47':'#2e6fdf'; ctx.lineWidth=3; ctx.beginPath(); ctx.moveTo(...pts[0]); pts.slice(1).forEach(p=>ctx.lineTo(...p)); ctx.stroke(); };
  const highlight = () => { if (tool !== 'highlight' || !materialRef.current) return; const sel=window.getSelection(); if(!sel || sel.isCollapsed || !materialRef.current.contains(sel.anchorNode)) return; const text=sel.toString(); const startIndex=data.material.indexOf(text); if(startIndex < 0) return; commit([...annotations, {id:uid(), type:'highlight', start:startIndex, end:startIndex+text.length, text, color:'yellow'}]); sel.removeAllRanges(); };
  const erase = (e: React.PointerEvent) => { if(tool!=='eraser') return; const p=point(e); const hit=annotations.find(a=>a.points?.some(q=>Math.hypot(q[0]-p[0],q[1]-p[1])<14)); if(hit) commit(annotations.filter(a=>a.id!==hit.id)); };
  const undo = () => { const prev=history.at(-1); if(!prev) return; setFuture(f=>[annotations,...f]); setHistory(history.slice(0,-1)); save(prev); }, redo = () => { const next=future.at(-1); if(!next) return; setHistory(h=>[...h,annotations]); setFuture(future.slice(0,-1)); save(next); };
  const html = useMemo(() => data ? marked.parse(data.material) : '', [data]);
  return <div className="app">
    <aside className={sidebarOpen?'sidebar':'sidebar collapsed'}>{sidebarOpen&&<><div className="side-title">内容目录 <button onClick={loadExams} title="刷新目录">↻</button></div>{exams.map(ex=><div key={ex.id} className="exam"><strong>⌄ {ex.name}</strong>{ex.items.map(it=><button key={it.id} className={selected?.exam===ex.id&&selected.item===it.id?'item active':'item'} onClick={()=>setSelected({exam:ex.id,item:it.id})}>📄 {it.name}{!it.valid&&<span className="warning">!</span>}</button>)}</div>)}</>}<button className="side-toggle" onClick={()=>setSidebarOpen(!sidebarOpen)} title={sidebarOpen?'收起目录':'展开目录'}>{sidebarOpen?'« 收起':'»'}</button></aside>
    <main className="main">
      {!data?<div className="empty"><div>✦</div><h2>选择一个试题组开始讲解</h2><p>从左侧目录选择材料与题目</p></div>:<div className="panes"><section className="material-pane"><div className="pane-head"><div><span className="eyebrow">READING MATERIAL</span><h2>{data.meta.name || selected?.item}</h2></div><span className="badge">{data.material.split(/\s+/).filter(Boolean).length} words</span></div><div className="material-scroll" ref={materialRef} onPointerDown={e=>{onDown(e);erase(e)}} onPointerMove={onMove} onPointerUp={onUp} onMouseUp={highlight}><article className="markdown" dangerouslySetInnerHTML={{__html:html as string}} />{annotations.filter(a=>a.type==='highlight').map(a=><span key={a.id} className="highlight-marker" title={a.text} />)}<canvas ref={canvasRef} className="annotation-canvas" /></div><div className="pane-foot"><button className={tool==='select'?'selected':''} onClick={()=>setTool('select')}>↖ 选择</button><button className={tool==='highlight'?'selected':''} onClick={()=>setTool('highlight')}>▰ 高亮</button><button className={tool==='freehand'?'selected':''} onClick={()=>setTool('freehand')}>〰 画笔</button><button className={tool==='line'?'selected':''} onClick={()=>setTool('line')}>╱ 直线</button><button className={tool==='eraser'?'selected':''} onClick={()=>setTool('eraser')}>⌫ 橡皮擦</button><span className="tool-hint">{tool==='highlight'?'选中文字即可高亮':tool==='eraser'?'点击批注删除':'拖拽进行标注'}</span><div className="foot-actions"><button onClick={undo} disabled={!history.length}>↶ 撤销</button><button onClick={redo} disabled={!future.length}>↷ 重做</button><button className="danger" onClick={()=>selected && save([])}>清空批注</button></div></div></section>
      <section className="questions-pane"><div className="pane-head"><div><span className="eyebrow">QUESTIONS</span><h2>题目讲解</h2></div><button className="answer-toggle" onClick={()=>{const all=data.questions.every((q:Question)=>showAnswers[q.id||'']); const n:any={}; data.questions.forEach((q:Question)=>n[q.id||'']=!all); setShowAnswers(n)}}>{data.questions.every((q:Question)=>showAnswers[q.id||''])?'隐藏全部答案':'预览全部答案'}</button></div><div className="questions">{data.questions.map((q:Question,i:number)=><div className="question" id={`question-${i+1}`} key={q.id||i}><div className="q-title"><span>{i+1}</span><b>{q.question}</b><button onClick={()=>setShowAnswers(s=>({...s,[q.id||String(i)]:!s[q.id||String(i)]}))}>{showAnswers[q.id||String(i)]?'隐藏答案':'预览答案'}</button></div><div className="options">{q.options.map(o=><div className={showAnswers[q.id||String(i)]&&o.key===q.answer?'option correct':'option'} key={o.key}><b>{o.key}</b>{o.text}</div>)}</div>{showAnswers[q.id||String(i)]&&<div className="explanation"><strong>答案：{q.answer}</strong>{q.explanation&&<p>{q.explanation}</p>}</div>}</div>)}</div></section></div>}
    </main>{changed&&<div className="change-toast">检测到数据文件变化 <button onClick={()=>location.reload()}>重新加载</button><button onClick={()=>setChanged(false)}>稍后</button></div>}</div>
}
createRoot(document.getElementById('root')!).render(<App />);
